-----------------------------------------------------------------------------------------
-- Title: 
-- Name: Your Name
-- Course: ICS2O/3C
-- This program creates math problems with random operators
-- (*,-,+,/)
-- main.lua
--
-----------------------------------------------------------------------------------------

-- Your code here